const age = 24;
const name = "hardik bandil"
const dob = "10/10/2000"

function sayName() {
console.log('My Name is ${name}')
}

function newFeatureadd() {
    console.log("this is new feature");
    console.log("this is add new feature");
}

function newFeatureadd2() {
    console.log("this is second feature");
    console.log("this is second latest feature");
}

function newFeatureadd3() {
    console.log("this is third feature");
    console.log("this is third latest feature");
}