const age = 24;
const name = "hardik bandil"
const dob = "10/10/2000"

function sayName() {
console.log('My Name is ${name}')
}

function newFeatureadd() {
    console.log("this is new feature");
    console.log("this is add new feature");
}

function newFeatureadd2() {
    console.log("this is second feature");
    console.log("this is second latest feature");
}

function newFeatureadd3() {
    console.log("this is third feature");
    console.log("this is third latest feature");
}

function newFeatureadd4() {
    console.log("this is fourth feature");
    console.log("this is fourth latest feature");
}


function newFeatureadd5() {
    console.log("this is fifth feature");
    console.log("this is fifth latest feature");
}


function newFeatureadd6() {
    console.log("this is sixth feature");
    console.log("this is sixth latest feature");
}

function newFeatureadd7() {
    console.log("this is seventh feature");
    console.log("this is seventh latest feature");
}